# version: '3'

services:
  app:
    build: .
    image: laravel-telescope
    container_name: laravel-telescope
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www/laravel-telescope
    volumes:
      - .:/var/www/laravel-telescope
      - ./storage/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-telescope

  webserver:
    image: nginx:alpine
    container_name: laravel-telescope-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "6003:80"
    volumes:
      - .:/var/www/laravel-telescope
      - ./storage/:/etc/nginx/conf.d/
    networks:
      - laravel-telescope

# Networks
networks:
  sanata-api-denpasar_sanata-dps:
    external: true
  laravel-telescope:
    driver: bridge
  # sanata-sgr_simrs-network:
  #   external: true
